### ISSUE TITLE
Enforcing/setting settings in other modules

### ISSUE THREAD

**Issue by bondjimbond** [bondjimbond/islandora_westvault#38]
Is it it possible to either enforce particular configurations in the Islandora Bagit module, or to pass particular configurations when using its functions?

This module is built with the assumption that particular configurations will be used; it would be nice to make sure that happens rather than just hoping for the best.

**Comment by mjordan** [comment]
Fraid not, Islandora BagIt only uses configuration data accessible from `variable_get()`. In my external (non-Drupal module) BagIt tools like https://github.com/mjordan/islandora_bagger (Islandora 8) and https://github.com/mjordan/islandora_fetch_bags (Islandora 7) I've put all configuration in external files.

That said, it might be possible to modify the Islandora BagIt module so that `islandora_bagit_create_bag()` and `islandora_bagit_create_object_bag_batch()` to accept an optional array of config variables, for example, that would override the admin settings variables. Have to think about this a bit more but that's my initial take on it.

**Comment by bondjimbond** [comment]
In #39 I do a simple `variable_get` from islandora_bagit.module to enforce the `plugin_ds_basic` setting. No reason I can see that this can't be done for all the required configurations..

**Comment by bondjimbond** [comment]
Sorted with #40.
